package com.generator.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.PRODUCT_ID
     *
     * @mbggenerated
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.PRODUCT_TYPE_ID
     *
     * @mbggenerated
     */
    private String productTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.PRIMARY_PRODUCT_CATEGORY_ID
     *
     * @mbggenerated
     */
    private String primaryProductCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.MANUFACTURER_PARTY_ID
     *
     * @mbggenerated
     */
    private String manufacturerPartyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.FACILITY_ID
     *
     * @mbggenerated
     */
    private String facilityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.INTRODUCTION_DATE
     *
     * @mbggenerated
     */
    private Date introductionDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.RELEASE_DATE
     *
     * @mbggenerated
     */
    private Date releaseDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.SUPPORT_DISCONTINUATION_DATE
     *
     * @mbggenerated
     */
    private Date supportDiscontinuationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.SALES_DISCONTINUATION_DATE
     *
     * @mbggenerated
     */
    private Date salesDiscontinuationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.SALES_DISC_WHEN_NOT_AVAIL
     *
     * @mbggenerated
     */
    private String salesDiscWhenNotAvail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.INTERNAL_NAME
     *
     * @mbggenerated
     */
    private String internalName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.BRAND_NAME
     *
     * @mbggenerated
     */
    private String brandName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.COMMENTS
     *
     * @mbggenerated
     */
    private String comments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.PRODUCT_NAME
     *
     * @mbggenerated
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.DESCRIPTION
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.PRICE_DETAIL_TEXT
     *
     * @mbggenerated
     */
    private String priceDetailText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.SMALL_IMAGE_URL
     *
     * @mbggenerated
     */
    private String smallImageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.MEDIUM_IMAGE_URL
     *
     * @mbggenerated
     */
    private String mediumImageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.LARGE_IMAGE_URL
     *
     * @mbggenerated
     */
    private String largeImageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.DETAIL_IMAGE_URL
     *
     * @mbggenerated
     */
    private String detailImageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.ORIGINAL_IMAGE_URL
     *
     * @mbggenerated
     */
    private String originalImageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.DETAIL_SCREEN
     *
     * @mbggenerated
     */
    private String detailScreen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.INVENTORY_MESSAGE
     *
     * @mbggenerated
     */
    private String inventoryMessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.REQUIRE_INVENTORY
     *
     * @mbggenerated
     */
    private String requireInventory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.QUANTITY_UOM_ID
     *
     * @mbggenerated
     */
    private String quantityUomId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.QUANTITY_INCLUDED
     *
     * @mbggenerated
     */
    private BigDecimal quantityIncluded;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.PIECES_INCLUDED
     *
     * @mbggenerated
     */
    private BigDecimal piecesIncluded;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.REQUIRE_AMOUNT
     *
     * @mbggenerated
     */
    private String requireAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.FIXED_AMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal fixedAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.AMOUNT_UOM_TYPE_ID
     *
     * @mbggenerated
     */
    private String amountUomTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.WEIGHT_UOM_ID
     *
     * @mbggenerated
     */
    private String weightUomId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.WEIGHT
     *
     * @mbggenerated
     */
    private BigDecimal weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.PRODUCT_WEIGHT
     *
     * @mbggenerated
     */
    private BigDecimal productWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.HEIGHT_UOM_ID
     *
     * @mbggenerated
     */
    private String heightUomId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.PRODUCT_HEIGHT
     *
     * @mbggenerated
     */
    private BigDecimal productHeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.SHIPPING_HEIGHT
     *
     * @mbggenerated
     */
    private BigDecimal shippingHeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.WIDTH_UOM_ID
     *
     * @mbggenerated
     */
    private String widthUomId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.PRODUCT_WIDTH
     *
     * @mbggenerated
     */
    private BigDecimal productWidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.SHIPPING_WIDTH
     *
     * @mbggenerated
     */
    private BigDecimal shippingWidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.DEPTH_UOM_ID
     *
     * @mbggenerated
     */
    private String depthUomId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.PRODUCT_DEPTH
     *
     * @mbggenerated
     */
    private BigDecimal productDepth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.SHIPPING_DEPTH
     *
     * @mbggenerated
     */
    private BigDecimal shippingDepth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.DIAMETER_UOM_ID
     *
     * @mbggenerated
     */
    private String diameterUomId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.PRODUCT_DIAMETER
     *
     * @mbggenerated
     */
    private BigDecimal productDiameter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.PRODUCT_RATING
     *
     * @mbggenerated
     */
    private BigDecimal productRating;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.RATING_TYPE_ENUM
     *
     * @mbggenerated
     */
    private String ratingTypeEnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.RETURNABLE
     *
     * @mbggenerated
     */
    private String returnable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.TAXABLE
     *
     * @mbggenerated
     */
    private String taxable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.CHARGE_SHIPPING
     *
     * @mbggenerated
     */
    private String chargeShipping;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.AUTO_CREATE_KEYWORDS
     *
     * @mbggenerated
     */
    private String autoCreateKeywords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.INCLUDE_IN_PROMOTIONS
     *
     * @mbggenerated
     */
    private String includeInPromotions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.IS_VIRTUAL
     *
     * @mbggenerated
     */
    private String isVirtual;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.IS_VARIANT
     *
     * @mbggenerated
     */
    private String isVariant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.VIRTUAL_VARIANT_METHOD_ENUM
     *
     * @mbggenerated
     */
    private String virtualVariantMethodEnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.ORIGIN_GEO_ID
     *
     * @mbggenerated
     */
    private String originGeoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.REQUIREMENT_METHOD_ENUM_ID
     *
     * @mbggenerated
     */
    private String requirementMethodEnumId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.BILL_OF_MATERIAL_LEVEL
     *
     * @mbggenerated
     */
    private BigDecimal billOfMaterialLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.RESERV_MAX_PERSONS
     *
     * @mbggenerated
     */
    private BigDecimal reservMaxPersons;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.RESERV2ND_P_P_PERC
     *
     * @mbggenerated
     */
    private BigDecimal reserv2ndPPPerc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.RESERV_NTH_P_P_PERC
     *
     * @mbggenerated
     */
    private BigDecimal reservNthPPPerc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.CONFIG_ID
     *
     * @mbggenerated
     */
    private String configId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.CREATED_DATE
     *
     * @mbggenerated
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.CREATED_BY_USER_LOGIN
     *
     * @mbggenerated
     */
    private String createdByUserLogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.LAST_MODIFIED_DATE
     *
     * @mbggenerated
     */
    private Date lastModifiedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.LAST_MODIFIED_BY_USER_LOGIN
     *
     * @mbggenerated
     */
    private String lastModifiedByUserLogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.IN_SHIPPING_BOX
     *
     * @mbggenerated
     */
    private String inShippingBox;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.DEFAULT_SHIPMENT_BOX_TYPE_ID
     *
     * @mbggenerated
     */
    private String defaultShipmentBoxTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.LOT_ID_FILLED_IN
     *
     * @mbggenerated
     */
    private String lotIdFilledIn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.ORDER_DECIMAL_QUANTITY
     *
     * @mbggenerated
     */
    private String orderDecimalQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.LAST_UPDATED_STAMP
     *
     * @mbggenerated
     */
    private Date lastUpdatedStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.LAST_UPDATED_TX_STAMP
     *
     * @mbggenerated
     */
    private Date lastUpdatedTxStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.CREATED_STAMP
     *
     * @mbggenerated
     */
    private Date createdStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.CREATED_TX_STAMP
     *
     * @mbggenerated
     */
    private Date createdTxStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.IS_SUPPORT_COD
     *
     * @mbggenerated
     */
    private String isSupportCod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.LIMIT_AMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal limitAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.IS_SHOW
     *
     * @mbggenerated
     */
    private String isShow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.EXTEND_NAME
     *
     * @mbggenerated
     */
    private String extendName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.PACKAGE_NAME
     *
     * @mbggenerated
     */
    private String packageName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.LONG_DESCRIPTION
     *
     * @mbggenerated
     */
    private String longDescription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.PRODUCT_ID
     *
     * @return the value of product.PRODUCT_ID
     *
     * @mbggenerated
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.PRODUCT_ID
     *
     * @param productId the value for product.PRODUCT_ID
     *
     * @mbggenerated
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.PRODUCT_TYPE_ID
     *
     * @return the value of product.PRODUCT_TYPE_ID
     *
     * @mbggenerated
     */
    public String getProductTypeId() {
        return productTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.PRODUCT_TYPE_ID
     *
     * @param productTypeId the value for product.PRODUCT_TYPE_ID
     *
     * @mbggenerated
     */
    public void setProductTypeId(String productTypeId) {
        this.productTypeId = productTypeId == null ? null : productTypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.PRIMARY_PRODUCT_CATEGORY_ID
     *
     * @return the value of product.PRIMARY_PRODUCT_CATEGORY_ID
     *
     * @mbggenerated
     */
    public String getPrimaryProductCategoryId() {
        return primaryProductCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.PRIMARY_PRODUCT_CATEGORY_ID
     *
     * @param primaryProductCategoryId the value for product.PRIMARY_PRODUCT_CATEGORY_ID
     *
     * @mbggenerated
     */
    public void setPrimaryProductCategoryId(String primaryProductCategoryId) {
        this.primaryProductCategoryId = primaryProductCategoryId == null ? null : primaryProductCategoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.MANUFACTURER_PARTY_ID
     *
     * @return the value of product.MANUFACTURER_PARTY_ID
     *
     * @mbggenerated
     */
    public String getManufacturerPartyId() {
        return manufacturerPartyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.MANUFACTURER_PARTY_ID
     *
     * @param manufacturerPartyId the value for product.MANUFACTURER_PARTY_ID
     *
     * @mbggenerated
     */
    public void setManufacturerPartyId(String manufacturerPartyId) {
        this.manufacturerPartyId = manufacturerPartyId == null ? null : manufacturerPartyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.FACILITY_ID
     *
     * @return the value of product.FACILITY_ID
     *
     * @mbggenerated
     */
    public String getFacilityId() {
        return facilityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.FACILITY_ID
     *
     * @param facilityId the value for product.FACILITY_ID
     *
     * @mbggenerated
     */
    public void setFacilityId(String facilityId) {
        this.facilityId = facilityId == null ? null : facilityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.INTRODUCTION_DATE
     *
     * @return the value of product.INTRODUCTION_DATE
     *
     * @mbggenerated
     */
    public Date getIntroductionDate() {
        return introductionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.INTRODUCTION_DATE
     *
     * @param introductionDate the value for product.INTRODUCTION_DATE
     *
     * @mbggenerated
     */
    public void setIntroductionDate(Date introductionDate) {
        this.introductionDate = introductionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.RELEASE_DATE
     *
     * @return the value of product.RELEASE_DATE
     *
     * @mbggenerated
     */
    public Date getReleaseDate() {
        return releaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.RELEASE_DATE
     *
     * @param releaseDate the value for product.RELEASE_DATE
     *
     * @mbggenerated
     */
    public void setReleaseDate(Date releaseDate) {
        this.releaseDate = releaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.SUPPORT_DISCONTINUATION_DATE
     *
     * @return the value of product.SUPPORT_DISCONTINUATION_DATE
     *
     * @mbggenerated
     */
    public Date getSupportDiscontinuationDate() {
        return supportDiscontinuationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.SUPPORT_DISCONTINUATION_DATE
     *
     * @param supportDiscontinuationDate the value for product.SUPPORT_DISCONTINUATION_DATE
     *
     * @mbggenerated
     */
    public void setSupportDiscontinuationDate(Date supportDiscontinuationDate) {
        this.supportDiscontinuationDate = supportDiscontinuationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.SALES_DISCONTINUATION_DATE
     *
     * @return the value of product.SALES_DISCONTINUATION_DATE
     *
     * @mbggenerated
     */
    public Date getSalesDiscontinuationDate() {
        return salesDiscontinuationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.SALES_DISCONTINUATION_DATE
     *
     * @param salesDiscontinuationDate the value for product.SALES_DISCONTINUATION_DATE
     *
     * @mbggenerated
     */
    public void setSalesDiscontinuationDate(Date salesDiscontinuationDate) {
        this.salesDiscontinuationDate = salesDiscontinuationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.SALES_DISC_WHEN_NOT_AVAIL
     *
     * @return the value of product.SALES_DISC_WHEN_NOT_AVAIL
     *
     * @mbggenerated
     */
    public String getSalesDiscWhenNotAvail() {
        return salesDiscWhenNotAvail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.SALES_DISC_WHEN_NOT_AVAIL
     *
     * @param salesDiscWhenNotAvail the value for product.SALES_DISC_WHEN_NOT_AVAIL
     *
     * @mbggenerated
     */
    public void setSalesDiscWhenNotAvail(String salesDiscWhenNotAvail) {
        this.salesDiscWhenNotAvail = salesDiscWhenNotAvail == null ? null : salesDiscWhenNotAvail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.INTERNAL_NAME
     *
     * @return the value of product.INTERNAL_NAME
     *
     * @mbggenerated
     */
    public String getInternalName() {
        return internalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.INTERNAL_NAME
     *
     * @param internalName the value for product.INTERNAL_NAME
     *
     * @mbggenerated
     */
    public void setInternalName(String internalName) {
        this.internalName = internalName == null ? null : internalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.BRAND_NAME
     *
     * @return the value of product.BRAND_NAME
     *
     * @mbggenerated
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.BRAND_NAME
     *
     * @param brandName the value for product.BRAND_NAME
     *
     * @mbggenerated
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName == null ? null : brandName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.COMMENTS
     *
     * @return the value of product.COMMENTS
     *
     * @mbggenerated
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.COMMENTS
     *
     * @param comments the value for product.COMMENTS
     *
     * @mbggenerated
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.PRODUCT_NAME
     *
     * @return the value of product.PRODUCT_NAME
     *
     * @mbggenerated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.PRODUCT_NAME
     *
     * @param productName the value for product.PRODUCT_NAME
     *
     * @mbggenerated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.DESCRIPTION
     *
     * @return the value of product.DESCRIPTION
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.DESCRIPTION
     *
     * @param description the value for product.DESCRIPTION
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.PRICE_DETAIL_TEXT
     *
     * @return the value of product.PRICE_DETAIL_TEXT
     *
     * @mbggenerated
     */
    public String getPriceDetailText() {
        return priceDetailText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.PRICE_DETAIL_TEXT
     *
     * @param priceDetailText the value for product.PRICE_DETAIL_TEXT
     *
     * @mbggenerated
     */
    public void setPriceDetailText(String priceDetailText) {
        this.priceDetailText = priceDetailText == null ? null : priceDetailText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.SMALL_IMAGE_URL
     *
     * @return the value of product.SMALL_IMAGE_URL
     *
     * @mbggenerated
     */
    public String getSmallImageUrl() {
        return smallImageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.SMALL_IMAGE_URL
     *
     * @param smallImageUrl the value for product.SMALL_IMAGE_URL
     *
     * @mbggenerated
     */
    public void setSmallImageUrl(String smallImageUrl) {
        this.smallImageUrl = smallImageUrl == null ? null : smallImageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.MEDIUM_IMAGE_URL
     *
     * @return the value of product.MEDIUM_IMAGE_URL
     *
     * @mbggenerated
     */
    public String getMediumImageUrl() {
        return mediumImageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.MEDIUM_IMAGE_URL
     *
     * @param mediumImageUrl the value for product.MEDIUM_IMAGE_URL
     *
     * @mbggenerated
     */
    public void setMediumImageUrl(String mediumImageUrl) {
        this.mediumImageUrl = mediumImageUrl == null ? null : mediumImageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.LARGE_IMAGE_URL
     *
     * @return the value of product.LARGE_IMAGE_URL
     *
     * @mbggenerated
     */
    public String getLargeImageUrl() {
        return largeImageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.LARGE_IMAGE_URL
     *
     * @param largeImageUrl the value for product.LARGE_IMAGE_URL
     *
     * @mbggenerated
     */
    public void setLargeImageUrl(String largeImageUrl) {
        this.largeImageUrl = largeImageUrl == null ? null : largeImageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.DETAIL_IMAGE_URL
     *
     * @return the value of product.DETAIL_IMAGE_URL
     *
     * @mbggenerated
     */
    public String getDetailImageUrl() {
        return detailImageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.DETAIL_IMAGE_URL
     *
     * @param detailImageUrl the value for product.DETAIL_IMAGE_URL
     *
     * @mbggenerated
     */
    public void setDetailImageUrl(String detailImageUrl) {
        this.detailImageUrl = detailImageUrl == null ? null : detailImageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.ORIGINAL_IMAGE_URL
     *
     * @return the value of product.ORIGINAL_IMAGE_URL
     *
     * @mbggenerated
     */
    public String getOriginalImageUrl() {
        return originalImageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.ORIGINAL_IMAGE_URL
     *
     * @param originalImageUrl the value for product.ORIGINAL_IMAGE_URL
     *
     * @mbggenerated
     */
    public void setOriginalImageUrl(String originalImageUrl) {
        this.originalImageUrl = originalImageUrl == null ? null : originalImageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.DETAIL_SCREEN
     *
     * @return the value of product.DETAIL_SCREEN
     *
     * @mbggenerated
     */
    public String getDetailScreen() {
        return detailScreen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.DETAIL_SCREEN
     *
     * @param detailScreen the value for product.DETAIL_SCREEN
     *
     * @mbggenerated
     */
    public void setDetailScreen(String detailScreen) {
        this.detailScreen = detailScreen == null ? null : detailScreen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.INVENTORY_MESSAGE
     *
     * @return the value of product.INVENTORY_MESSAGE
     *
     * @mbggenerated
     */
    public String getInventoryMessage() {
        return inventoryMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.INVENTORY_MESSAGE
     *
     * @param inventoryMessage the value for product.INVENTORY_MESSAGE
     *
     * @mbggenerated
     */
    public void setInventoryMessage(String inventoryMessage) {
        this.inventoryMessage = inventoryMessage == null ? null : inventoryMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.REQUIRE_INVENTORY
     *
     * @return the value of product.REQUIRE_INVENTORY
     *
     * @mbggenerated
     */
    public String getRequireInventory() {
        return requireInventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.REQUIRE_INVENTORY
     *
     * @param requireInventory the value for product.REQUIRE_INVENTORY
     *
     * @mbggenerated
     */
    public void setRequireInventory(String requireInventory) {
        this.requireInventory = requireInventory == null ? null : requireInventory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.QUANTITY_UOM_ID
     *
     * @return the value of product.QUANTITY_UOM_ID
     *
     * @mbggenerated
     */
    public String getQuantityUomId() {
        return quantityUomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.QUANTITY_UOM_ID
     *
     * @param quantityUomId the value for product.QUANTITY_UOM_ID
     *
     * @mbggenerated
     */
    public void setQuantityUomId(String quantityUomId) {
        this.quantityUomId = quantityUomId == null ? null : quantityUomId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.QUANTITY_INCLUDED
     *
     * @return the value of product.QUANTITY_INCLUDED
     *
     * @mbggenerated
     */
    public BigDecimal getQuantityIncluded() {
        return quantityIncluded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.QUANTITY_INCLUDED
     *
     * @param quantityIncluded the value for product.QUANTITY_INCLUDED
     *
     * @mbggenerated
     */
    public void setQuantityIncluded(BigDecimal quantityIncluded) {
        this.quantityIncluded = quantityIncluded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.PIECES_INCLUDED
     *
     * @return the value of product.PIECES_INCLUDED
     *
     * @mbggenerated
     */
    public BigDecimal getPiecesIncluded() {
        return piecesIncluded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.PIECES_INCLUDED
     *
     * @param piecesIncluded the value for product.PIECES_INCLUDED
     *
     * @mbggenerated
     */
    public void setPiecesIncluded(BigDecimal piecesIncluded) {
        this.piecesIncluded = piecesIncluded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.REQUIRE_AMOUNT
     *
     * @return the value of product.REQUIRE_AMOUNT
     *
     * @mbggenerated
     */
    public String getRequireAmount() {
        return requireAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.REQUIRE_AMOUNT
     *
     * @param requireAmount the value for product.REQUIRE_AMOUNT
     *
     * @mbggenerated
     */
    public void setRequireAmount(String requireAmount) {
        this.requireAmount = requireAmount == null ? null : requireAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.FIXED_AMOUNT
     *
     * @return the value of product.FIXED_AMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getFixedAmount() {
        return fixedAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.FIXED_AMOUNT
     *
     * @param fixedAmount the value for product.FIXED_AMOUNT
     *
     * @mbggenerated
     */
    public void setFixedAmount(BigDecimal fixedAmount) {
        this.fixedAmount = fixedAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.AMOUNT_UOM_TYPE_ID
     *
     * @return the value of product.AMOUNT_UOM_TYPE_ID
     *
     * @mbggenerated
     */
    public String getAmountUomTypeId() {
        return amountUomTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.AMOUNT_UOM_TYPE_ID
     *
     * @param amountUomTypeId the value for product.AMOUNT_UOM_TYPE_ID
     *
     * @mbggenerated
     */
    public void setAmountUomTypeId(String amountUomTypeId) {
        this.amountUomTypeId = amountUomTypeId == null ? null : amountUomTypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.WEIGHT_UOM_ID
     *
     * @return the value of product.WEIGHT_UOM_ID
     *
     * @mbggenerated
     */
    public String getWeightUomId() {
        return weightUomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.WEIGHT_UOM_ID
     *
     * @param weightUomId the value for product.WEIGHT_UOM_ID
     *
     * @mbggenerated
     */
    public void setWeightUomId(String weightUomId) {
        this.weightUomId = weightUomId == null ? null : weightUomId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.WEIGHT
     *
     * @return the value of product.WEIGHT
     *
     * @mbggenerated
     */
    public BigDecimal getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.WEIGHT
     *
     * @param weight the value for product.WEIGHT
     *
     * @mbggenerated
     */
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.PRODUCT_WEIGHT
     *
     * @return the value of product.PRODUCT_WEIGHT
     *
     * @mbggenerated
     */
    public BigDecimal getProductWeight() {
        return productWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.PRODUCT_WEIGHT
     *
     * @param productWeight the value for product.PRODUCT_WEIGHT
     *
     * @mbggenerated
     */
    public void setProductWeight(BigDecimal productWeight) {
        this.productWeight = productWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.HEIGHT_UOM_ID
     *
     * @return the value of product.HEIGHT_UOM_ID
     *
     * @mbggenerated
     */
    public String getHeightUomId() {
        return heightUomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.HEIGHT_UOM_ID
     *
     * @param heightUomId the value for product.HEIGHT_UOM_ID
     *
     * @mbggenerated
     */
    public void setHeightUomId(String heightUomId) {
        this.heightUomId = heightUomId == null ? null : heightUomId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.PRODUCT_HEIGHT
     *
     * @return the value of product.PRODUCT_HEIGHT
     *
     * @mbggenerated
     */
    public BigDecimal getProductHeight() {
        return productHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.PRODUCT_HEIGHT
     *
     * @param productHeight the value for product.PRODUCT_HEIGHT
     *
     * @mbggenerated
     */
    public void setProductHeight(BigDecimal productHeight) {
        this.productHeight = productHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.SHIPPING_HEIGHT
     *
     * @return the value of product.SHIPPING_HEIGHT
     *
     * @mbggenerated
     */
    public BigDecimal getShippingHeight() {
        return shippingHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.SHIPPING_HEIGHT
     *
     * @param shippingHeight the value for product.SHIPPING_HEIGHT
     *
     * @mbggenerated
     */
    public void setShippingHeight(BigDecimal shippingHeight) {
        this.shippingHeight = shippingHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.WIDTH_UOM_ID
     *
     * @return the value of product.WIDTH_UOM_ID
     *
     * @mbggenerated
     */
    public String getWidthUomId() {
        return widthUomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.WIDTH_UOM_ID
     *
     * @param widthUomId the value for product.WIDTH_UOM_ID
     *
     * @mbggenerated
     */
    public void setWidthUomId(String widthUomId) {
        this.widthUomId = widthUomId == null ? null : widthUomId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.PRODUCT_WIDTH
     *
     * @return the value of product.PRODUCT_WIDTH
     *
     * @mbggenerated
     */
    public BigDecimal getProductWidth() {
        return productWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.PRODUCT_WIDTH
     *
     * @param productWidth the value for product.PRODUCT_WIDTH
     *
     * @mbggenerated
     */
    public void setProductWidth(BigDecimal productWidth) {
        this.productWidth = productWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.SHIPPING_WIDTH
     *
     * @return the value of product.SHIPPING_WIDTH
     *
     * @mbggenerated
     */
    public BigDecimal getShippingWidth() {
        return shippingWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.SHIPPING_WIDTH
     *
     * @param shippingWidth the value for product.SHIPPING_WIDTH
     *
     * @mbggenerated
     */
    public void setShippingWidth(BigDecimal shippingWidth) {
        this.shippingWidth = shippingWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.DEPTH_UOM_ID
     *
     * @return the value of product.DEPTH_UOM_ID
     *
     * @mbggenerated
     */
    public String getDepthUomId() {
        return depthUomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.DEPTH_UOM_ID
     *
     * @param depthUomId the value for product.DEPTH_UOM_ID
     *
     * @mbggenerated
     */
    public void setDepthUomId(String depthUomId) {
        this.depthUomId = depthUomId == null ? null : depthUomId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.PRODUCT_DEPTH
     *
     * @return the value of product.PRODUCT_DEPTH
     *
     * @mbggenerated
     */
    public BigDecimal getProductDepth() {
        return productDepth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.PRODUCT_DEPTH
     *
     * @param productDepth the value for product.PRODUCT_DEPTH
     *
     * @mbggenerated
     */
    public void setProductDepth(BigDecimal productDepth) {
        this.productDepth = productDepth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.SHIPPING_DEPTH
     *
     * @return the value of product.SHIPPING_DEPTH
     *
     * @mbggenerated
     */
    public BigDecimal getShippingDepth() {
        return shippingDepth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.SHIPPING_DEPTH
     *
     * @param shippingDepth the value for product.SHIPPING_DEPTH
     *
     * @mbggenerated
     */
    public void setShippingDepth(BigDecimal shippingDepth) {
        this.shippingDepth = shippingDepth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.DIAMETER_UOM_ID
     *
     * @return the value of product.DIAMETER_UOM_ID
     *
     * @mbggenerated
     */
    public String getDiameterUomId() {
        return diameterUomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.DIAMETER_UOM_ID
     *
     * @param diameterUomId the value for product.DIAMETER_UOM_ID
     *
     * @mbggenerated
     */
    public void setDiameterUomId(String diameterUomId) {
        this.diameterUomId = diameterUomId == null ? null : diameterUomId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.PRODUCT_DIAMETER
     *
     * @return the value of product.PRODUCT_DIAMETER
     *
     * @mbggenerated
     */
    public BigDecimal getProductDiameter() {
        return productDiameter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.PRODUCT_DIAMETER
     *
     * @param productDiameter the value for product.PRODUCT_DIAMETER
     *
     * @mbggenerated
     */
    public void setProductDiameter(BigDecimal productDiameter) {
        this.productDiameter = productDiameter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.PRODUCT_RATING
     *
     * @return the value of product.PRODUCT_RATING
     *
     * @mbggenerated
     */
    public BigDecimal getProductRating() {
        return productRating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.PRODUCT_RATING
     *
     * @param productRating the value for product.PRODUCT_RATING
     *
     * @mbggenerated
     */
    public void setProductRating(BigDecimal productRating) {
        this.productRating = productRating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.RATING_TYPE_ENUM
     *
     * @return the value of product.RATING_TYPE_ENUM
     *
     * @mbggenerated
     */
    public String getRatingTypeEnum() {
        return ratingTypeEnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.RATING_TYPE_ENUM
     *
     * @param ratingTypeEnum the value for product.RATING_TYPE_ENUM
     *
     * @mbggenerated
     */
    public void setRatingTypeEnum(String ratingTypeEnum) {
        this.ratingTypeEnum = ratingTypeEnum == null ? null : ratingTypeEnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.RETURNABLE
     *
     * @return the value of product.RETURNABLE
     *
     * @mbggenerated
     */
    public String getReturnable() {
        return returnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.RETURNABLE
     *
     * @param returnable the value for product.RETURNABLE
     *
     * @mbggenerated
     */
    public void setReturnable(String returnable) {
        this.returnable = returnable == null ? null : returnable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.TAXABLE
     *
     * @return the value of product.TAXABLE
     *
     * @mbggenerated
     */
    public String getTaxable() {
        return taxable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.TAXABLE
     *
     * @param taxable the value for product.TAXABLE
     *
     * @mbggenerated
     */
    public void setTaxable(String taxable) {
        this.taxable = taxable == null ? null : taxable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.CHARGE_SHIPPING
     *
     * @return the value of product.CHARGE_SHIPPING
     *
     * @mbggenerated
     */
    public String getChargeShipping() {
        return chargeShipping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.CHARGE_SHIPPING
     *
     * @param chargeShipping the value for product.CHARGE_SHIPPING
     *
     * @mbggenerated
     */
    public void setChargeShipping(String chargeShipping) {
        this.chargeShipping = chargeShipping == null ? null : chargeShipping.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.AUTO_CREATE_KEYWORDS
     *
     * @return the value of product.AUTO_CREATE_KEYWORDS
     *
     * @mbggenerated
     */
    public String getAutoCreateKeywords() {
        return autoCreateKeywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.AUTO_CREATE_KEYWORDS
     *
     * @param autoCreateKeywords the value for product.AUTO_CREATE_KEYWORDS
     *
     * @mbggenerated
     */
    public void setAutoCreateKeywords(String autoCreateKeywords) {
        this.autoCreateKeywords = autoCreateKeywords == null ? null : autoCreateKeywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.INCLUDE_IN_PROMOTIONS
     *
     * @return the value of product.INCLUDE_IN_PROMOTIONS
     *
     * @mbggenerated
     */
    public String getIncludeInPromotions() {
        return includeInPromotions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.INCLUDE_IN_PROMOTIONS
     *
     * @param includeInPromotions the value for product.INCLUDE_IN_PROMOTIONS
     *
     * @mbggenerated
     */
    public void setIncludeInPromotions(String includeInPromotions) {
        this.includeInPromotions = includeInPromotions == null ? null : includeInPromotions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.IS_VIRTUAL
     *
     * @return the value of product.IS_VIRTUAL
     *
     * @mbggenerated
     */
    public String getIsVirtual() {
        return isVirtual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.IS_VIRTUAL
     *
     * @param isVirtual the value for product.IS_VIRTUAL
     *
     * @mbggenerated
     */
    public void setIsVirtual(String isVirtual) {
        this.isVirtual = isVirtual == null ? null : isVirtual.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.IS_VARIANT
     *
     * @return the value of product.IS_VARIANT
     *
     * @mbggenerated
     */
    public String getIsVariant() {
        return isVariant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.IS_VARIANT
     *
     * @param isVariant the value for product.IS_VARIANT
     *
     * @mbggenerated
     */
    public void setIsVariant(String isVariant) {
        this.isVariant = isVariant == null ? null : isVariant.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.VIRTUAL_VARIANT_METHOD_ENUM
     *
     * @return the value of product.VIRTUAL_VARIANT_METHOD_ENUM
     *
     * @mbggenerated
     */
    public String getVirtualVariantMethodEnum() {
        return virtualVariantMethodEnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.VIRTUAL_VARIANT_METHOD_ENUM
     *
     * @param virtualVariantMethodEnum the value for product.VIRTUAL_VARIANT_METHOD_ENUM
     *
     * @mbggenerated
     */
    public void setVirtualVariantMethodEnum(String virtualVariantMethodEnum) {
        this.virtualVariantMethodEnum = virtualVariantMethodEnum == null ? null : virtualVariantMethodEnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.ORIGIN_GEO_ID
     *
     * @return the value of product.ORIGIN_GEO_ID
     *
     * @mbggenerated
     */
    public String getOriginGeoId() {
        return originGeoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.ORIGIN_GEO_ID
     *
     * @param originGeoId the value for product.ORIGIN_GEO_ID
     *
     * @mbggenerated
     */
    public void setOriginGeoId(String originGeoId) {
        this.originGeoId = originGeoId == null ? null : originGeoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.REQUIREMENT_METHOD_ENUM_ID
     *
     * @return the value of product.REQUIREMENT_METHOD_ENUM_ID
     *
     * @mbggenerated
     */
    public String getRequirementMethodEnumId() {
        return requirementMethodEnumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.REQUIREMENT_METHOD_ENUM_ID
     *
     * @param requirementMethodEnumId the value for product.REQUIREMENT_METHOD_ENUM_ID
     *
     * @mbggenerated
     */
    public void setRequirementMethodEnumId(String requirementMethodEnumId) {
        this.requirementMethodEnumId = requirementMethodEnumId == null ? null : requirementMethodEnumId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.BILL_OF_MATERIAL_LEVEL
     *
     * @return the value of product.BILL_OF_MATERIAL_LEVEL
     *
     * @mbggenerated
     */
    public BigDecimal getBillOfMaterialLevel() {
        return billOfMaterialLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.BILL_OF_MATERIAL_LEVEL
     *
     * @param billOfMaterialLevel the value for product.BILL_OF_MATERIAL_LEVEL
     *
     * @mbggenerated
     */
    public void setBillOfMaterialLevel(BigDecimal billOfMaterialLevel) {
        this.billOfMaterialLevel = billOfMaterialLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.RESERV_MAX_PERSONS
     *
     * @return the value of product.RESERV_MAX_PERSONS
     *
     * @mbggenerated
     */
    public BigDecimal getReservMaxPersons() {
        return reservMaxPersons;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.RESERV_MAX_PERSONS
     *
     * @param reservMaxPersons the value for product.RESERV_MAX_PERSONS
     *
     * @mbggenerated
     */
    public void setReservMaxPersons(BigDecimal reservMaxPersons) {
        this.reservMaxPersons = reservMaxPersons;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.RESERV2ND_P_P_PERC
     *
     * @return the value of product.RESERV2ND_P_P_PERC
     *
     * @mbggenerated
     */
    public BigDecimal getReserv2ndPPPerc() {
        return reserv2ndPPPerc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.RESERV2ND_P_P_PERC
     *
     * @param reserv2ndPPPerc the value for product.RESERV2ND_P_P_PERC
     *
     * @mbggenerated
     */
    public void setReserv2ndPPPerc(BigDecimal reserv2ndPPPerc) {
        this.reserv2ndPPPerc = reserv2ndPPPerc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.RESERV_NTH_P_P_PERC
     *
     * @return the value of product.RESERV_NTH_P_P_PERC
     *
     * @mbggenerated
     */
    public BigDecimal getReservNthPPPerc() {
        return reservNthPPPerc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.RESERV_NTH_P_P_PERC
     *
     * @param reservNthPPPerc the value for product.RESERV_NTH_P_P_PERC
     *
     * @mbggenerated
     */
    public void setReservNthPPPerc(BigDecimal reservNthPPPerc) {
        this.reservNthPPPerc = reservNthPPPerc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.CONFIG_ID
     *
     * @return the value of product.CONFIG_ID
     *
     * @mbggenerated
     */
    public String getConfigId() {
        return configId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.CONFIG_ID
     *
     * @param configId the value for product.CONFIG_ID
     *
     * @mbggenerated
     */
    public void setConfigId(String configId) {
        this.configId = configId == null ? null : configId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.CREATED_DATE
     *
     * @return the value of product.CREATED_DATE
     *
     * @mbggenerated
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.CREATED_DATE
     *
     * @param createdDate the value for product.CREATED_DATE
     *
     * @mbggenerated
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.CREATED_BY_USER_LOGIN
     *
     * @return the value of product.CREATED_BY_USER_LOGIN
     *
     * @mbggenerated
     */
    public String getCreatedByUserLogin() {
        return createdByUserLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.CREATED_BY_USER_LOGIN
     *
     * @param createdByUserLogin the value for product.CREATED_BY_USER_LOGIN
     *
     * @mbggenerated
     */
    public void setCreatedByUserLogin(String createdByUserLogin) {
        this.createdByUserLogin = createdByUserLogin == null ? null : createdByUserLogin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.LAST_MODIFIED_DATE
     *
     * @return the value of product.LAST_MODIFIED_DATE
     *
     * @mbggenerated
     */
    public Date getLastModifiedDate() {
        return lastModifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.LAST_MODIFIED_DATE
     *
     * @param lastModifiedDate the value for product.LAST_MODIFIED_DATE
     *
     * @mbggenerated
     */
    public void setLastModifiedDate(Date lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.LAST_MODIFIED_BY_USER_LOGIN
     *
     * @return the value of product.LAST_MODIFIED_BY_USER_LOGIN
     *
     * @mbggenerated
     */
    public String getLastModifiedByUserLogin() {
        return lastModifiedByUserLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.LAST_MODIFIED_BY_USER_LOGIN
     *
     * @param lastModifiedByUserLogin the value for product.LAST_MODIFIED_BY_USER_LOGIN
     *
     * @mbggenerated
     */
    public void setLastModifiedByUserLogin(String lastModifiedByUserLogin) {
        this.lastModifiedByUserLogin = lastModifiedByUserLogin == null ? null : lastModifiedByUserLogin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.IN_SHIPPING_BOX
     *
     * @return the value of product.IN_SHIPPING_BOX
     *
     * @mbggenerated
     */
    public String getInShippingBox() {
        return inShippingBox;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.IN_SHIPPING_BOX
     *
     * @param inShippingBox the value for product.IN_SHIPPING_BOX
     *
     * @mbggenerated
     */
    public void setInShippingBox(String inShippingBox) {
        this.inShippingBox = inShippingBox == null ? null : inShippingBox.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.DEFAULT_SHIPMENT_BOX_TYPE_ID
     *
     * @return the value of product.DEFAULT_SHIPMENT_BOX_TYPE_ID
     *
     * @mbggenerated
     */
    public String getDefaultShipmentBoxTypeId() {
        return defaultShipmentBoxTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.DEFAULT_SHIPMENT_BOX_TYPE_ID
     *
     * @param defaultShipmentBoxTypeId the value for product.DEFAULT_SHIPMENT_BOX_TYPE_ID
     *
     * @mbggenerated
     */
    public void setDefaultShipmentBoxTypeId(String defaultShipmentBoxTypeId) {
        this.defaultShipmentBoxTypeId = defaultShipmentBoxTypeId == null ? null : defaultShipmentBoxTypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.LOT_ID_FILLED_IN
     *
     * @return the value of product.LOT_ID_FILLED_IN
     *
     * @mbggenerated
     */
    public String getLotIdFilledIn() {
        return lotIdFilledIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.LOT_ID_FILLED_IN
     *
     * @param lotIdFilledIn the value for product.LOT_ID_FILLED_IN
     *
     * @mbggenerated
     */
    public void setLotIdFilledIn(String lotIdFilledIn) {
        this.lotIdFilledIn = lotIdFilledIn == null ? null : lotIdFilledIn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.ORDER_DECIMAL_QUANTITY
     *
     * @return the value of product.ORDER_DECIMAL_QUANTITY
     *
     * @mbggenerated
     */
    public String getOrderDecimalQuantity() {
        return orderDecimalQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.ORDER_DECIMAL_QUANTITY
     *
     * @param orderDecimalQuantity the value for product.ORDER_DECIMAL_QUANTITY
     *
     * @mbggenerated
     */
    public void setOrderDecimalQuantity(String orderDecimalQuantity) {
        this.orderDecimalQuantity = orderDecimalQuantity == null ? null : orderDecimalQuantity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.LAST_UPDATED_STAMP
     *
     * @return the value of product.LAST_UPDATED_STAMP
     *
     * @mbggenerated
     */
    public Date getLastUpdatedStamp() {
        return lastUpdatedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.LAST_UPDATED_STAMP
     *
     * @param lastUpdatedStamp the value for product.LAST_UPDATED_STAMP
     *
     * @mbggenerated
     */
    public void setLastUpdatedStamp(Date lastUpdatedStamp) {
        this.lastUpdatedStamp = lastUpdatedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.LAST_UPDATED_TX_STAMP
     *
     * @return the value of product.LAST_UPDATED_TX_STAMP
     *
     * @mbggenerated
     */
    public Date getLastUpdatedTxStamp() {
        return lastUpdatedTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.LAST_UPDATED_TX_STAMP
     *
     * @param lastUpdatedTxStamp the value for product.LAST_UPDATED_TX_STAMP
     *
     * @mbggenerated
     */
    public void setLastUpdatedTxStamp(Date lastUpdatedTxStamp) {
        this.lastUpdatedTxStamp = lastUpdatedTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.CREATED_STAMP
     *
     * @return the value of product.CREATED_STAMP
     *
     * @mbggenerated
     */
    public Date getCreatedStamp() {
        return createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.CREATED_STAMP
     *
     * @param createdStamp the value for product.CREATED_STAMP
     *
     * @mbggenerated
     */
    public void setCreatedStamp(Date createdStamp) {
        this.createdStamp = createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.CREATED_TX_STAMP
     *
     * @return the value of product.CREATED_TX_STAMP
     *
     * @mbggenerated
     */
    public Date getCreatedTxStamp() {
        return createdTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.CREATED_TX_STAMP
     *
     * @param createdTxStamp the value for product.CREATED_TX_STAMP
     *
     * @mbggenerated
     */
    public void setCreatedTxStamp(Date createdTxStamp) {
        this.createdTxStamp = createdTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.IS_SUPPORT_COD
     *
     * @return the value of product.IS_SUPPORT_COD
     *
     * @mbggenerated
     */
    public String getIsSupportCod() {
        return isSupportCod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.IS_SUPPORT_COD
     *
     * @param isSupportCod the value for product.IS_SUPPORT_COD
     *
     * @mbggenerated
     */
    public void setIsSupportCod(String isSupportCod) {
        this.isSupportCod = isSupportCod == null ? null : isSupportCod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.LIMIT_AMOUNT
     *
     * @return the value of product.LIMIT_AMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getLimitAmount() {
        return limitAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.LIMIT_AMOUNT
     *
     * @param limitAmount the value for product.LIMIT_AMOUNT
     *
     * @mbggenerated
     */
    public void setLimitAmount(BigDecimal limitAmount) {
        this.limitAmount = limitAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.IS_SHOW
     *
     * @return the value of product.IS_SHOW
     *
     * @mbggenerated
     */
    public String getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.IS_SHOW
     *
     * @param isShow the value for product.IS_SHOW
     *
     * @mbggenerated
     */
    public void setIsShow(String isShow) {
        this.isShow = isShow == null ? null : isShow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.EXTEND_NAME
     *
     * @return the value of product.EXTEND_NAME
     *
     * @mbggenerated
     */
    public String getExtendName() {
        return extendName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.EXTEND_NAME
     *
     * @param extendName the value for product.EXTEND_NAME
     *
     * @mbggenerated
     */
    public void setExtendName(String extendName) {
        this.extendName = extendName == null ? null : extendName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.PACKAGE_NAME
     *
     * @return the value of product.PACKAGE_NAME
     *
     * @mbggenerated
     */
    public String getPackageName() {
        return packageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.PACKAGE_NAME
     *
     * @param packageName the value for product.PACKAGE_NAME
     *
     * @mbggenerated
     */
    public void setPackageName(String packageName) {
        this.packageName = packageName == null ? null : packageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.LONG_DESCRIPTION
     *
     * @return the value of product.LONG_DESCRIPTION
     *
     * @mbggenerated
     */
    public String getLongDescription() {
        return longDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.LONG_DESCRIPTION
     *
     * @param longDescription the value for product.LONG_DESCRIPTION
     *
     * @mbggenerated
     */
    public void setLongDescription(String longDescription) {
        this.longDescription = longDescription == null ? null : longDescription.trim();
    }
}